### ISSUE TITLE
Type exception in Python3 `TypeError: 'type' object is not subscriptable`

### ISSUE THREAD

**Issue by jesuscast** [dotenv-org/dotenv-vault-python#5]
The following exception happens when running on Python 3.8.12
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jesuscastanedasosa/dev/notopensource/env3/lib/python3.8/site-packages/dotenv_vault/__init__.py", line 1, in <module>
    from .main import load_dotenv
  File "/Users/jesuscastanedasosa/dev/notopensource/env3/lib/python3.8/site-packages/dotenv_vault/main.py", line 6, in <module>
    from .vault import DotEnvVault
  File "/Users/jesuscastanedasosa/dev/notopensource/env3/lib/python3.8/site-packages/dotenv_vault/vault.py", line 16, in <module>
    class DotEnvVault(): #vault stuff
  File "/Users/jesuscastanedasosa/dev/notopensource/env3/lib/python3.8/site-packages/dotenv_vault/vault.py", line 89, in DotEnvVault
    def _key_rotation(self, keys: list[dict]) -> str:
TypeError: 'type' object is not subscriptable
```
list[dict] is only available in Python 3.9+

It's not clear anywhere that you expect users to use Python 3.9. This is a very bleeding edge requirement and most existing codebases cannot support it.

Please make the library backwards compatible with at least 3.8+

**Comment by nsnguyen** [comment]
This is merged and bumped version to 0.3.0
